### ISSUE TITLE
Build error because of missed ZstdNet.1.0.0 package

### ISSUE THREAD

**Issue by VitaliyMF** [killwort/ClickHouse-Net#1]
It seems ClickHouse.Ado.csproj has references to 'ZstdNet' package that is no longer needed and causes build errors:

>   <Import Project="..\packages\ZstdNet.1.0.0\build\ZstdNet.targets" Condition="Exists('..\packages\ZstdNet.1.0.0\build\ZstdNet.targets')" />

I haven't tested the connector yet mostly because I have .NET Core appplication.
Do you have any plans to add nestandard build? I see that only non-common dependency is 'lz4net' and it already has netstandard build ( https://www.nuget.org/packages/lz4net/ ).

Also I think it is good idea to publish 'ClickHouse.Ado' on nuget :-)

BTW, I can help with these 2 things: migrate csproj to VS-2017 format that supports multiple targets at once (net451 / netstandard1.x) and nuget package generation with 'dotnet pack'.

**Comment by killwort** [comment]
I have plans for .net core version, actually I stripped off all dependencies (e.g. System.Data) to use in minimal environment, however that led to disabling compression at all.
If you could, please help with multitarget VS-2017 project as I haven't much time to dig into it. Just fork/do pull request.

**Comment by VitaliyMF** [comment]
@killwort  

> If you could, please help with multitarget VS-2017 project as I haven't much time to dig into it. Just fork/do pull request.

I'm going to do that this weekend and back to you with the results. Compression should be preserved as it is important in my usage scenario (BI tool connector to ClickHouse).

**Comment by killwort** [comment]
I've packaged/published this driver to nuget and will update it when something significant arrive (e.g. bugfix), so when you finish adding features consider moving to binary distribution.

**Comment by killwort** [comment]
Also I've added coco/r executable and included parser/scanner files regeneration prior to each build.

**Comment by VitaliyMF** [comment]
@killwort awsome, thanks!
