### ISSUE TITLE
@bulk vs array

### ISSUE THREAD

**Issue by Fallenyasha** [killwort/ClickHouse-Net#100]
В случае если в балке передается первым массив (точно проявляется при вставке массива строк, иные типы не проверялись), то вставка не выполняется.

Например таблица имеет описание: key Array(String), value String
Если вставлять INSERT INTO some_table (key, value) VALUES @bulk, то данные не вставляются, ошибок нет, таблица пустая.
Если поменять поля местами и вставлять INSERT INTO some_table (value, key) VALUES @bulk, то все отлично.

Пробовал делать как при помощи IEnumerable, так и при помощи IBulkInsertEnumerable, результат одинаков.

Соответственно если таблица содержит хотя бы одну скалярную колонку, то можно поставить ее первой при балке и все ок, но если таблица состоит только из массивов, или вставлять нужно только массивы, то вставить балком не представляется возможным.

**Comment by killwort** [comment]
Поправлено, будет в релизе 1.2.3
