### ISSUE TITLE
Bulk insert affected row count is always 0

### ISSUE THREAD

**Issue by ibradwan** [killwort/ClickHouse-Net#105]
## Description
Hi team, I have been using the Clickhouse.Ado C# NuGet to insert into our own **distributed** CH table. Here's the code snippet:
```csharp
this.connection
    .CreateCommand($"INSERT INTO {tableName} ({string.Join(',', columns)}) VALUES @bulk")
    .AddParameter("bulk", DbType.Object, payload)
    .ExecuteNonQuery();
```
It works properly and the rows get ingested into the CH table, but the returned value of this call is always `0`. I want to get the number of inserted rows. Is there something that I need to add/setup?

My connection string looks like this:
`Compress=True;CheckCompressedHash=False;Compressor=lz4;Host=xyz.trafficmanager.net;Port=9000;User=xyz_user;Password=xyz_pass;SocketTimeout=600000;Database=xyz_db;`

**Comment by killwort** [comment]
Hi,
Sadly, CH does not respond to inserts with the number of affected row, so I cannot pass that value over to your application.
