### ISSUE TITLE
Unable to cast object of type 'DrainageType' to type 'System.Nullable`1[System.Int32]'.

### ISSUE THREAD

**Issue by agoling** [killwort/ClickHouse-Net#112]
ERROR:Unable to cast object of type 'DrainageType' to type 'System.Nullable`1[System.Int32]'.

DrainageType is a enum 

this is my model
![image](https://user-images.githubusercontent.com/37896493/104534076-8c869480-564e-11eb-973e-a7ad29604acd.png)

this is create table field
![image](https://user-images.githubusercontent.com/37896493/104534139-aa53f980-564e-11eb-883a-7ca5ca1afbc2.png)

but when i insert error: Unable to cast object of type 'DrainageType' to type 'System.Nullable`1[System.Int32]'.

**Comment by agoling** [comment]
https://clickhouse.tech/docs/zh/sql-reference/data-types/enum/

**Comment by killwort** [comment]
Enums in clickhouse work like strings. So if you're using @bulk inserts you should return string values (.ToString()) for these fields and if you're using single-value parameters you may set parameter type to string and use string enum representation anyway.
From architectural point of view it might be better to reconsider your table structure to use String column for enumerables 'cause it will free you from the pain of synchronizing enum value lists between clickhouse table model and .net enum model.
