### ISSUE TITLE
On time zone modification

### ISSUE THREAD

**Issue by 1228912823** [killwort/ClickHouse-Net#113]
The time zone has been configured in the Clickhouse client, but the time is wrong when the program inserts the time zone. Does the program support importing the time zone to make the time correct

**Comment by killwort** [comment]
In clickhouse date/time values are stored as difference (in seconds) between the given time value and unixtime epoch (1970-01-01 00:00:00Z).
The driver mimics that behavior by subtracting unixtime epoch constant (with DateTimeKind.Utc) from your values. So you should probably set correct TZ in your dates on the input or use UTC dates. On the output side dates are always returned in DateTimeKind.Utc.

Timezone data is not transferred along with the data as it is only kept in the table structure.
