### ISSUE TITLE
How to assign batch size and parallelism to TCP Ingestion in Clickhouse

### ISSUE THREAD

**Issue by Kalyancsaripalli** [killwort/ClickHouse-Net#115]
We want to try TCP Ingestion and was searching for documentation on how to assign batch size or increase parallelism

TCP:
 await Task.Run(() =>
                    this.connection
                        .CreateCommand($"INSERT INTO {tableName} ({string.Join(',', columns)}) VALUES @bulk")
                        .AddParameter("bulk", DbType.Object, payload)
                        .ExecuteNonQuery());

HTTP: Here I can assign BatchSize and Parallelism. How can i do something similar for TCP
var bulkCopyInterface = new ClickHouseBulkCopy(this.connection);
            bulkCopyInterface.DestinationTableName = targetTable;
            bulkCopyInterface.BatchSize = httpBatchSize;
            bulkCopyInterface.MaxDegreeOfParallelism = maxDegreeOfParallelism;

            await bulkCopyInterface.WriteToServerAsync(httpPayload, columns);

**Comment by killwort** [comment]
My connections/commands are not thread safe! You should never share the same connection (and thus readers) between multiple threads.
So the best thought is to use connection per thread/task.
