### ISSUE TITLE
ClickHouseException: Decimals with length >= 28 are not supported (.NET framework decimal range limit)

### ISSUE THREAD

**Issue by VitaliyMF** [killwort/ClickHouse-Net#117]
## Description

ClickHouse may have Decimal data type with a higher precision that .NET Decimal can represent. In this case it throws an exception in [DecimalColumnType.cs](https://github.com/killwort/ClickHouse-Net/blob/master/ClickHouse.Ado/Impl/ColumnTypes/DecimalColumnType.cs):

```
        public DecimalColumnType(uint length, uint precision) {
            _length = length;
            _precision = precision;
            if (_length >= 28)
                throw new ClickHouseException("Decimals with length >= 28 are not supported (.NET framework decimal range limit)");
```

I think this can be handled on ClickHouse.Ado driver if value can be rounded to the precision that may be loaded into .NET Decimal - in this way Oracle ADO.NET driver works (they introduced special "SuppressGetDecimalInvalidCastException" option for this purpose).  It seems this is possible with minimal changes as anyway "Read" and "Write" implementations use "BigInteger".

**Comment by killwort** [comment]
What is the point in using precision unhandleable by the client? This would definitely lead to weird errors when you try to round-trip values through your app.

Moreover, these errors cannot be safely ignored as they're integer overflow errors so they will lead to losing most-significant digits instead of losing precision with least-significant digits.

**Comment by killwort** [comment]
On the second thought, I'm really using BigInteger which allows reading 128-bit numbers, so I could relatively safely lift my 64-bit limit (however numbers will be treated as non-precise decimals!)

**Comment by VitaliyMF** [comment]
`What is the point in using precision unhandleable by the client?`

Real-life case: ClickHouse.Ado is used in my BI tool (SeekTable), it is primarily about summary reports like pivot tables / charts. When sum/avg is used over high-precision decimals it cannot be loaded an hacks like "CAST( SUM(high_precision_decimal_col) as Decimal64(18))" is only way to get the report. At the same time, actually high-precision in sum/avg values is not needed at all, usually it is anyway rounded to just several digits after a decimal point.

**Comment by killwort** [comment]
The problem is not with the precision, it is with the scale! Clickhouse's Decimal128 can contain values up to 10^38, while .net is limited with 10^28. There's no way to represent these values in .net.
I'll try to change the limitation to be precision-scale<=28 instead of current precision<=28 and run some tests.

**Comment by VitaliyMF** [comment]
Yeah it is not possible to load really large CH-decimal into .NET decimal. What if ClickHouse.Ado will return high-precision CH-decimals as .NET doubles? This behavior may be controlled with a connection string option, if you don't want to apply it by default.

**Comment by killwort** [comment]
That is possible, yet it will lead to even greater loss of precision (doubles are 64bit with 17 significant digits)

**Comment by VitaliyMF** [comment]
In my use-case, loss of precision is acceptable and this is much better than just an exception :) if this will be controlled with the connection string option, this behavior may be chosen when it is acceptable -- like in the Oracle ADO.NET driver mentioned above.

**Comment by killwort** [comment]
Haha, i've tried to implement that. And here's what i've got:
Column: Decimal(38,4)
Inserting value: 10e30 (double const in code) => 9.9999999999999996E+30 (actual double value)
Value in database: 9999999999999999686336610791797.5552
Roundtrip result: 9.9999999999999996E+30 (actual double value)

The test passes!

However the price is UGLY code, as now I have **if** branches for

- int32 represented numbers
- int64 represented numbers
- BigInteger represented numbers with integer parts <10^28 and fractional precision <28
- BigInteger represented numbers with integer parts <10^28 and fractional precision >=28
- BigInteger represented numbers with integer parts >10^28 (cast to double)

**Comment by VitaliyMF** [comment]
@killwort that was really fast! Many-many thanks! )

> However the price is UGLY code, as now I have if branches for

It works, and this is only thing that has matter, actually.
