### ISSUE TITLE
Add SQL DDL scripts for local test run

### ISSUE THREAD

**Issue by bratchikov** [killwort/ClickHouse-Net#118]
## Description
Missed ClickHouse database when start tests in VS.

## Steps to reproduce
1. Clone repo
2. Open solution in VS2019
3. Rebuild
4. Run all tests

## Workarounds
Create same test tables by query statements.

## What should be done
Please put CreateDB.sql for local tests run. May be move connection strings to tests App.config.

**Comment by killwort** [comment]
There're SQL scripts in some newer test classes (in OneTimeSetUp methods).
Sadly, there's no scripts for older tests in SimpleTests and I do not have any plan/free time for adding them.
