### ISSUE TITLE
Incorrect parsing insert sql with \" into string value

### ISSUE THREAD

**Issue by bratchikov** [killwort/ClickHouse-Net#119]
## Description
Insert sql query with `\"` like this does not work:
```sql
insert into vince_test values ('2017-05-17 00:00:00','CSA_C[{\"field\":\"Field11\"}]PT\"Y1233',0)
```
## Steps to reproduce
1. Create insert query with \" in string value
2. Execute this query
3. ClickHouse does not send response, get connection hanging

## Workarounds
Do not use \" in the query :)

## What should be done
Test for this case added. Insert query with \" into string value successfully executed.

## Details
Детальный разбор проблемы опишу на русском, мне так проще объяснить сложные вещи.
Как выяснилось, проблема была добавлена [моим PR-ом](https://github.com/killwort/ClickHouse-Net/pull/64), в котором была реализована поддержка Guid-ов (не суть) и, самое главное, допускался вариант экранирования полей в виде \".
В [документации к ClickHouse указывается](https://clickhouse.tech/docs/ru/sql-reference/syntax/#syntax-identifiers), что поля могут экранироваться двумя вариантами: \` или ". 
В моём проекте SQL генерируется именно в варианте с \", поэтому данная функция важна. Теоретически можно заменить и на \`, но хорошо бы поддержать стандартные возможности ClickHouse.
Суть проблемы уходит [в эту строку в ATG](https://github.com/killwort/ClickHouse-Net/blob/2e58187445acdccb3b8c8eb1895c882f6c2877eb/ClickHouse.Ado/Impl/ATG/Insert/Insert.atg#L18).  
Если убрать из этой строки ", то перестают работать запросы вида:
```
INSERT INTO "StoredClass" ( "primaryKey", "StoredProperty" ) VALUES ('7a25da2e-e1bc-4d73-8068-ec4cc507c649','abc')
```
Причём, такой запрос тоже не проходит:
```
INSERT INTO `StoredClass` ( `primaryKey`, `StoredProperty` ) VALUES ('7a25da2e-e1bc-4d73-8068-ec4cc507c649','[{\"field\":\"Field11\"}]')
```
В конечном виде нам хочется выполнять такие запросы:
```
INSERT INTO "StoredClass" ( "primaryKey", "StoredProperty" ) VALUES ('7a25da2e-e1bc-4d73-8068-ec4cc507c649','[{\"field\":\"Field11\"}]')
```
ATG мне не знаком, самостоятельно быстро решить вопрос не получилось.

**Comment by killwort** [comment]
Я починил ` для идентификаторов и \" внутри констант. Мне всё равно не понятно почему нельзя было использовать параметры или даже @bulk insert.
