### ISSUE TITLE
Library is hard locked on old System.Data.Common="4.3.0" and System.Threading.Thread="4.3.0"

### ISSUE THREAD

**Issue by vvit1** [killwort/ClickHouse-Net#127]
Hi Andrey,

I've tried to use your lib in .NET5 project with EF=5.0.9 and other db providers like npgl. 
When I try to publish the project got linker conflict with System.Data.Common="4.3.0" and System.Threading.Thread="4.3.0" that is hard linked in your lib.
(By default .NET5 comes with 5.0.20 versions of this libs)

Is it necessary linking like this?

**Comment by killwort** [comment]
I've targeted net5.0 and removed these direct dependencies. Will be available in 1.4.1+ (releasing later today).
