### ISSUE TITLE
EF Core Use DBConnection rather than IDbConnection

### ISSUE THREAD

**Issue by huiyuanai709** [killwort/ClickHouse-Net#130]
Try to use EF Core wrapper ado.net, but EF Core IRelationalConnection use DbConnection rather than IDbConnection

**Comment by killwort** [comment]
That's not an easy 5-minutes-work & commit task. Can't say when I will have time to do that.
If you want, you could do it yourself and pull request it here.

**Comment by killwort** [comment]
2.0.0-preview will solve that. However I think it is not production ready for now.
