### ISSUE TITLE
Advantages of TCP over HTTP

### ISSUE THREAD

**Issue by Astimus** [killwort/ClickHouse-Net#132]
Hi. I'm sorry for asking the question here.
What are the advantages of `TCP` over the `HTTP` `ClickHouse `interface? (performance, reliability, security, maintainability, support of different formats like parquet and arrow, streaming support)
As I understand, It is much harder to support Native format and interface because of lack of specification. Most likely, `Apache Parquet`+ `HTTP` does not lose in speed to the native interface. 
Why have you decided to implement the library on the native interface? Thank you in advance.

**Comment by killwort** [comment]
TCP-based proto has less overhead, it does not require HTTP headers and stuff. Moreover, TCP-based proto is designed to keep connection open and has support for arbitrarily sized transfers up and down, while HTTP has limitations and each command require a separate session (connection). 
Both protocols are completely insecure, however DPI filters can interfere with clickhouse HTTP traffic and could not do it with native protocol.
