### ISSUE TITLE
no connection to clickhouse in Yandex.Cloud

### ISSUE THREAD

**Issue by zabavin** [killwort/ClickHouse-Net#133]
## Description
 
no connection to clickhouse in Yandex.Cloud
with SSL
 ClickHouseConnectionSettings settings = new ClickHouseConnectionSettings("Encrypt=True;Database=XXXX;Host=XXX-whmjckgzq7j69mvb.mdb.yandexcloud.net;Port=8443;User=xxxxx;Password=xxxxxx;");
  string connectionString = settings.ToString();
                using (ClickHouseConnection ch_conn = new ClickHouseConnection(connectionString)) 
  {......
 

"ch_conn.ServerInfo" выдал исключение типа "System.NullReferenceException"

without Encrypt=True;
 ClickHouseConnectionSettings settings = new ClickHouseConnectionSettings("Database=XXXX;Host=XXX-whmjckgzq7j69mvb.mdb.yandexcloud.net;Port=8443;User=xxxxx;Password=xxxxxx;");
  string connectionString = settings.ToString();
                using (ClickHouseConnection ch_conn = new ClickHouseConnection(connectionString)) 
  {......
"ch_conn.ServerInfo" выдал исключение типа "System.NullReferenceException"

if i'm connect good on ODBC driver :) this https://github.com/ClickHouse/clickhouse-odbc 
But I don't wont use this/

**Comment by zabavin** [comment]
ClickHouseConnectionSettings settings = new ClickHouseConnectionSettings("Encrypt=True;Database=XXXX;Host=XXX-whmjckgzq7j69mvb.mdb.yandexcloud.net;Port=8443;User=xxxxx;Password=xxxxxx;");
string connectionString = settings.ToString();
using (ClickHouseConnection ch_conn = new ClickHouseConnection(connectionString))
{......

"ch_conn.ServerInfo" выдал исключение типа "System.NullReferenceException"

without Encrypt=True;
ClickHouseConnectionSettings settings = new ClickHouseConnectionSettings("Database=XXXX;Host=XXX-whmjckgzq7j69mvb.mdb.yandexcloud.net;Port=8443;User=xxxxx;Password=xxxxxx;");
string connectionString = settings.ToString();
using (ClickHouseConnection ch_conn = new ClickHouseConnection(connectionString))
{......
"ch_conn.ServerInfo" выдал исключение типа "System.NullReferenceException"

if i'm connect good on ODBC driver :) this https://github.com/ClickHouse/clickhouse-odbc
But I don't wont use this/

**Comment by killwort** [comment]
Sadly I do not have access to the yandex cloud (and even do not have own clickhouse SSL server).

And it seems that there's a problem in your code, clickhouse.ado does not have ch_conn symbol anywhere. Probably you're trying to get ServerInfo on non-open connection. ServerInfo is populated only after the connection is Open().
