### ISSUE TITLE
Sometimes the command can take 60 minutes without being terminated 

### ISSUE THREAD

**Issue by ggu123456** [killwort/ClickHouse-Net#134]
## Description
The comandtimeout property is not in use. I found sometimes the command can take 60 minutes without being terminated 

Is there a way to cancel a command?

**Comment by AlexeyAG** [comment]
Interface IDbCommand has Cancel method but it is not emplemented yet.
Is it possible to emplement this feature at nearest future or some future?

**Comment by killwort** [comment]
The short answer is no, there's no cancellation support or plans to implement that.

There's a long story behind that, implementing cancellation will require a major rework on code and additional reverse engineering of CH's native proto and I do not have resources for anything like that.

**Comment by killwort** [comment]
The workaround for cancelling a command is to close its connection (in another thread). That will definetely lead to exceptions being thrown in the waiting thread.
