### ISSUE TITLE
Make ClickHouseCommand derive DbCommand instead of IDbCommand directly

### ISSUE THREAD

**Issue by hmoush95** [killwort/ClickHouse-Net#135]
A lot of our already put in place Database Utility code (which works for a variety of different types of dbs and drivers) expects a DbCommand object passed in to execute the command. Unfortunately, ClickHouseCommand implements IDbCommand but does not derive DbCommand.

If it's not too difficult, it would be fantastic if it could also derive the object for greater compatibility with existing systems!

**Comment by hmoush95** [comment]
Seems like issue #130 have a similar request

**Comment by killwort** [comment]
Closing as duplicate #130
