### ISSUE TITLE
Connection pooling question

### ISSUE THREAD

**Issue by maxkornev** [killwort/ClickHouse-Net#136]
Hi!

Didn't find anywhere in the documentation, how to create connections. 
I see that in the test project the connection creates per request

```
internal class ConnectionHandler
    {
        public static ClickHouseConnection GetConnection(
            string cstr = "Compress=False;BufferSize=32768;SocketTimeout=10000;CheckCompressedHash=False;Encrypt=False;Compressor=lz4;Host=ch-test.flippingbook.com;Port=9000;Database=default;User=andreya;Password=123")
        {
            var settings = new ClickHouseConnectionSettings(cstr);
            var cnn = new ClickHouseConnection(settings);
            cnn.Open();
            return cnn;
        }
    }
```

However, I suppose that creating a connection on each request could cause some performance issues. I know that ado net uses connections pooling to avoid frequent db connections opening. 
Could you recommend how to create connections properly using Clickhouse-ado ?

**Comment by killwort** [comment]
Hi,
Sadly, clickhouse native protocol doesn't have any self-synchronization capability, so it is safer to have short lived connections. Moreover, connection handshake consists only of couple of packets and closing just disconnects underlaying socket, so there's not much overhead in having multiple connections.
Secondly, clickhouse typical workload includes huge and somewhat long running queries which live better in their own connections (as they cannot be multiplexed). The re-connection performance should not be an issue in that scenario. And if you need something like >10 requests per second from a single app instance you probably doing something wrong.
Third reason to keep connections as short as possible is that clickhouse is not transactional database so there's no point in keeping connection open for the duration of the transaction. Despite that you can put all your 'unit-of-work' queries in one connections sequentally, that will probably work :)
If you wish (and have reliable connection between client and server) you could easily set up connection pooling using ObjectPool<T> or something similar.
