### ISSUE TITLE
Как подключиться к ClickHouse через proxy сервер?

### ISSUE THREAD

**Issue by TimurChik73** [killwort/ClickHouse-Net#137]
Есть необходимость создавать подключение к ClickHouse через proxy сервер.
У конкурирующих библиотек для этого в конструкторе ClickHouseConnektion(string connectionString, HttpClient httpClient) есть второй параметр httpClient.
Добавьте пожалуйста возможность создавать подключение к ClickHouse через proxy сервер.

**Comment by killwort** [comment]
Моя библиотека не может работать через прокси, так как не использует протокол HTTP. VPN и другие "прозрачные" технологии должны работать.
