### ISSUE TITLE
Can't select more than 8 fields from clickhouse due to Tuple.

### ISSUE THREAD

**Issue by Zerorigin** [killwort/ClickHouse-Net#140]
Can't select more than 8 fields from clickhouse due to `Tuple`.

https://docs.microsoft.com/en-us/dotnet/api/system.valuetuple-8?view=net-6.0

```
SELECT f1, f2, f3, f4, f5, f6, f7, f8, f9 FROM db.table WHERE ID = 'UUID' LIMIT 10;
```

**Comment by killwort** [comment]
Can't say I understand the problem described here.
