### ISSUE TITLE
Does syntaxis exists to cast data types?

### ISSUE THREAD

**Issue by RomanOlegovich** [killwort/ClickHouse-Net#143]
## Description
Can I use something like this?
"insert into FactOrder values (**toInt8**(@OrderId))"

**Comment by killwort** [comment]
Nope, query parser in driver does not support such syntax. 
By the way, you have control over parameter type/value, why do you need explicit cast?
And, as clickhouse documentation states, you shouldn't use one-row inserts, check info in README here for more efficient way of inserting.

**Comment by RomanOlegovich** [comment]
@killwort 
I want to import rows from Postgres
```
select OrderId, **some sql** as IsFirstOrder from orders
```
and export to ClickHouse
```
insert into FactOrder values @bulk
```
Both database has boolean db type for IsFirstOrder.

But in c# code IsFirstOrder has different db types: Boolean in postgres and DbByte in clickhouse.
```
System.InvalidCastException: 'Unable to cast object of type 'System.Boolean' to type 'System.SByte'.'
```

How I can cast postgres:boolean to clickhouse:boolean in this case?

**Comment by killwort** [comment]
When you implement IEnumerable interface in your object, do casts on return, like that:
`
class MyDataObject:IEnumerable{
public bool SomeBooleanFieldStoredInUInt8{get;set;}
....
public IEnumerator GetEnumerator(){
...
yield return SomeBooleanFieldStoredInUInt8?(byte)1:(byte)0;
}
}
`

**Comment by RomanOlegovich** [comment]
the idea is that all the code should be in sql, and c # does not know what data will be there, c # code can only call DbCommand for reading and writing.

**Comment by RomanOlegovich** [comment]
I think it may be a part of your sdk.
DBNull -> (object)null
Bool => sbyte
