### ISSUE TITLE
Does @bulk insert use pagination over IEnumerable?

### ISSUE THREAD

**Issue by RomanOlegovich** [killwort/ClickHouse-Net#145]
if pass an IEnumerable (1 million objects) will all the data be inserted in one go?  whether it is necessary to break the initial data into packs of data (thousands of objects each) for @bulk insert?

**Comment by killwort** [comment]
It will go in one big pack. However it wouldn't lead to proportional traffic increase 'cuz data is compressed on the way and most column types do deduplication before transfer too.
