### ISSUE TITLE
Add support to read DateTime offsets

### ISSUE THREAD

**Issue by rsibanez89** [killwort/ClickHouse-Net#148]
## Description
Can you add support for DateTime offsets?
Clickhouse DateTime column supports offsets but C# DateTime doesn't.

## Steps to reproduce
Execute this query which should return the `DateTime + the offset`, example: `2023-02-10T12:06:01+11:00`
```
SELECT toDateTime(now(), 'Australia/Sydney');
```

In C# if you use: `row.GetDateTime(i)` you lose the offset, which makes sense because its not supported by the type.
So you get back  `2023-02-10T12:06:01`

But if you use `row.GetString(i)` I would expect to read the whole cell. 
However, seems like the underlying code is converting the cell to `DateTime` and then back to `string`.

## What should be done
- You could change the `GetString` to read the whole cell as string.
- You could add a new `GetDateTimeOffset` in the ClickHouseDataReader. `C# DateTimeOffset` supports `DateTime + offset`.

**Comment by killwort** [comment]
It is impossible.
Check clickhouse docs:
https://clickhouse.com/docs/en/sql-reference/data-types/date32

That type does not store TZ offset information, only number of seconds since unix epoch. No cast on C# side would get that info back.

**Comment by rsibanez89** [comment]
@killwort Sure you are right, `Clickhouse Date32` doesn't support offset.
But I'm talking about `Clickhouse DateTime`.

Check this simple query:
```
SELECT toDateTime(now(), 'Australia/Sydney') AS column, toTypeName(column) AS column_type;
```

![image](https://user-images.githubusercontent.com/2132638/218055250-6f505500-0e46-4c83-b4e8-fdd35e5c51e7.png)

**Comment by killwort** [comment]
DateTime does not contain TZ info too. Actually, column type contains it DateTime('Australia/Sydney') however it is not contained in the values. Thus, all values in the column have same TZ and you actually supplied that TZ in your SQL. That's not driver's responsibility to parse and convert TZ offset, moreover, TZs in clickhouse are represented in 'unix style' strings and .net doesn't know anything about these values and cannot convert them to correct TZ offset.

Although it might seem easy to retain full TZ info while reading response (see ColumnType.cs, line 116) yet from the client code you'll never be able to read it in any reasonable way as ADO completely hides that 'complexity'.
