### ISSUE TITLE
Can't use bulk insert when object have least one property is null

### ISSUE THREAD

**Issue by tuana2k38** [killwort/ClickHouse-Net#149]
## Description
  I have the exception: throw new FormatException($"Column count in parameter table ({num}) doesn't match column count in schema ({block.Columns.Count})."); (line 134, ClickHouseCommand.cs).

## Steps to reproduce
There are my data sample and table:
{
	"MarketID": "STX",
	"TransactTime": "090030069",
	"MarketIndexClass": "2",
	"IndexsTypeCode": "201",
	"Currency": "VND",
	"InvestCode": "7000",
	"SellVolume": 0,
	"SellTradeAmount": 0,
	"BuyVolume": 0,
	"BuyTradedAmount": 0,
	"BondClassificationCode": null,
	"SecurityGroupID": null
}

CREATE TABLE OntDb.BufferInvestorPerIndustry
(

    `MarketID` String,

    `TransactTime` DateTime,

    `MarketIndexClass` String,

    `IndexsTypeCode` String,

    `Currency` String,

    `InvestCode` String,

    `SellVolume` Int32,

    `SellTradeAmount` Float32,

    `BuyVolume` Int32,

    `BuyTradedAmount` Float32,

    `BondClassificationCode` Nullable(String),

    `SecurityGroupID` Nullable(String)
)
ENGINE = Buffer('OntDb',
 'InvestorPerIndustry',
 16,
 10,
 100,
 1000,
 10000,
 100000,
 1000000);
It has 2 properties are null. So when program meet the statement: "int num = source.First().OfType<object>().Count();" num's value is 10 and  it does'n match the column count. I know that because null isn't object type.
Please help me to resolve this issue

## Workarounds
My temporary solution is set default value when it is null:
CreateMap<InvestorPerIndustry, DtoInvestorPerIndustry>()
    .ForMember(dest => dest.BondClassificationCode, opts => opts.MapFrom(src => src.BondClassificationCode ?? "N/A"))
    .ForMember(dest => dest.SecurityGroupID, opts => opts.MapFrom(src => src.SecurityGroupID ?? "N/A"))
But it's incorrect data!

## What should be done
... if you know what should be done to mitigate the issue, provide it here ...

**Comment by killwort** [comment]
You probably use very old version, please update to the latest.
If you check the source https://github.com/killwort/ClickHouse-Net/blob/da6f8760770d134d03644dc65c5a65bda5b06125/ClickHouse.Ado/ClickHouseCommand.cs#L95 you could see that it allows (and counts) nulls as values since 2019.

**Comment by tuana2k38** [comment]
It's work. Thank you!
