### ISSUE TITLE
how to set timezone in current connect

### ISSUE THREAD

**Issue by xibaoning** [killwort/ClickHouse-Net#153]
ConnectString:  "...TimeZone=UTC"  :  ERROR
Cmd: ClickHouseCommand("SET TIME ZONE 'UTC'") : ERROR

other way ?

**Comment by killwort** [comment]
https://clickhouse.com/docs/en/operations/settings/settings#session_timezone

**Comment by xibaoning** [comment]
## question2
on server clickhouse-client:  SELECT
    now(),
    timezone()
┌───────────────now()─┬─timezone()────┐
│ 2023-07-04 15:29:06 │ Asia/Shanghai │
└─────────────────────┴───────────────┘

C# code:
```C#
var zone = ExecuteScalar<string>("select timezone()");
Console.WriteLine(zone); //Asia/Shanghai
var servertime = ExecuteScalar<DateTime>("select now()");
 Console.WriteLine(servertime); // 2023-07-04 7:29:06 
```
 less 8 hours,how to get 2023-07-04 15:29:06 in C#

**Comment by killwort** [comment]
Read #148 - it explains why it is impossible.
