### ISSUE TITLE
Driver hangs when inserting into ReplicatedMergeTree tables

### ISSUE THREAD

**Issue by DenZhuv** [killwort/ClickHouse-Net#154]
## Description
Hello! I've encountered the following issue:

When executing queries like "_INSERT INTO...SELECT...FROM_" on **ReplicatedMergeThree** tables, the driver hangs and only returns the result when the query timeout is reached (one hour). However, the actual query execution takes only a couple of seconds.

Previously, this query was performed with **MergeTree** tables, but there was no such problem.
I use **ExecuteNonQuery** method for executing my queries.

## Steps to reproduce
ClickHouse.Ado version 1.5.5

1. Create MergeTree table with data (DataTable)
2. Create MergeTree table with squeezed data (SqueezedData)
3. Run "_INSERT INTO SqueezedData (columns) SELECT (columns) FROM DataTable GROUP BY (some_columns)_" with **ExecuteNonQuery** method
4. It`s OK

BUT
1. Cluster with 3 hosts
2. Create ReplicatedMergeTree table with data (DataTable)
3. Create ReplicatedMergeTree table with squeezed data (SqueezedData)
4. Run "_INSERT INTO SqueezedData (columns) SELECT (columns) FROM DataTable GROUP BY (some_columns_)" with **ExecuteNonQuery** method
5. ??? the driver hangs

## Workarounds
The same issue occurs with queries like "_ALTER TABLE...ON CLUSTER...ADD COLUMN_".
I found a temporary solution for it: 
Instead of using the **ExecuteNonQuery** method, I run the query with **ExecuteReader**  and then simply read all the results (for ReplicatedMergeTree it returns host names in the cluster). In this case driver works fast.
```
public static void ReadAndClose(this IDataReader reader)
{
    if (reader is null)
        throw new ArgumentNullException(nameof(reader));
    do
    {
        // I don't care
    }
    while (reader.NextResult() || reader.IsClosed);
}
```
However, for "_INSERT INTO...SELECT...FROM_", this solution doesn't work because the **NextResult()** method throws the exception:
```
System.IO.IOException: Unable to read data from the transport connection: Connection timed out.
 ---> System.Net.Sockets.SocketException (110): Connection timed out
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at ClickHouse.Ado.Impl.ProtocolFormatter.ReadBytes(Int32 i, Int32 size)
   at ClickHouse.Ado.Impl.ProtocolFormatter.ReadByte()
   at ClickHouse.Ado.Impl.ProtocolFormatter.ReadUInt()
   at ClickHouse.Ado.Impl.ProtocolFormatter.ReadPacket(Response rv)
   at ClickHouse.Ado.Impl.ProtocolFormatter.ReadBlock()
   at ClickHouse.Ado.ClickHouseDataReader.NextResult()
```

## What I want to know

- Is there any specific approach to working with ReplicatedMergeTree tables, especially when it comes to "INSERT INTO...SELECT...FROM" queries?
- Does the internal "insert query parser" have any impact on the behavior of queries for MergeTree and ReplicatedMergeTree tables?
- Could there be an issue on my end causing this behavior?

**Comment by killwort** [comment]
1. I'm using ReplicatedMergeTree daily without any problems on insert/update. Probably there's some issue when TLS is used, 'cause i've recently tried secure connection and bumped into the same timeout/read beyond end of stream exceptions. I will explore that problem more soon.
2. Query parser completely rewrites INSERT queries, as Clickhouse uses slightly different syntax in the VALUES part. Although there's no behavioral differences for different table engines.
3. Probably no.

**Comment by killwort** [comment]
Side note for 2. INSERT ... SELECT queries are not rewritten, as they don't contain any data supplied by client (parameters).

**Comment by killwort** [comment]
Ok, 2.0.0-preview is kinda ready. Still it is PREVIEW version, do not try to use in production.
https://www.nuget.org/packages/ClickHouse.Ado/2.0.0-preview

For now it has only net7 target, I plan to add net462 soon.
Plus it uses really outdated lz4 library, i'll think about moving to something more modern.

**Comment by DenZhuv** [comment]
Thank you for the answers. 
I will check the behavior of version 2.0 in the test environment. For my side, I partially got rid of the use of problematic functionality, but I am glad that the problem has already been solved in the new version.

**Comment by killwort** [comment]
2.0.2-preview is released, with updated LZ4 lib, and targeting net462, netstd2.1 and net6/7
