### ISSUE TITLE
Inserting multiple rows doesn't work returns an timeout error

### ISSUE THREAD

**Issue by xyb213405** [killwort/ClickHouse-Net#156]
public int InsertBulkDemo()
 {
    
     try
     {
         if (_clickHouseConnection.State == ConnectionState.Broken)
         {
             _clickHouseConnection.Close();
         }

         if (_clickHouseConnection.State == ConnectionState.Closed)
         {
             _clickHouseConnection.Open();
         }
         ClickHouseCommand cmd = _clickHouseConnection.CreateCommand();
       
         string sql = @"INSERT INTO testtable (WpNum,content) values (1,'test1'),(2,'test2');";
         cmd.CommandText = sql;
         return cmd.ExecuteNonQuery();
     }
     catch (Exception ex)
     {
         _logger.LogError($"ExecuteList<T> Exception  Exception Message：{ex.Message}");
     }
     return 0;
 `}```

**Comment by xyb213405** [comment]
![企业微信截图_1697788113104](https://github.com/killwort/ClickHouse-Net/assets/62739208/5ecff380-39ec-4646-94e4-5f753304c3b3)

**Comment by killwort** [comment]
Which version are you using? 1.x or 2.x?

**Comment by xyb213405** [comment]
this is  the version
<img width="435" alt="d8f8984b635cfb558b21d5afbcb3fa5" src="https://github.com/killwort/ClickHouse-Net/assets/62739208/7d389557-4adb-4e2e-9e5d-2fc775a3811a">

**Comment by killwort** [comment]
I've tried inserting multiple rows in one query with 1.5.5 and it succeeded without any problems.
Probably you're hitting the bug with encrypted connections. Try one of the following:
- Disable encryption (Encrypt=false in the connection string)
- Use 1.5.5-no-polling-on-tls version if you have to leave the encryption enabled
- Use 2.x version, although it is still preview/experimental.
