### ISSUE TITLE
DataTable.Load(DbDataReader) has a wrong hadppend   Can't  use it  in this way？ 

### ISSUE THREAD

**Issue by xyb213405** [killwort/ClickHouse-Net#159]
```
    _clickHouseConnection.Open();
    ClickHouseCommand cmd = _clickHouseConnection.CreateCommand();
    cmd.CommandText = sql;
    cmd.CommandType = commandType;
    foreach (ClickHouseParameter param in parameters)
        cmd.Parameters.Add(param);
    IDataReader reader = cmd.ExecuteReader();
    dt.Load(reader);
```

**Comment by xyb213405** [comment]
![image](https://github.com/killwort/ClickHouse-Net/assets/62739208/9ebf0fa8-7883-4713-9d9b-31a2ca671db3)

**Comment by xyb213405** [comment]
![image](https://github.com/killwort/ClickHouse-Net/assets/62739208/9e19f83d-0b21-4958-b8dd-42094f0c5e2e)
why always return  multiple result sets  I want to return single result set  but it does not work?

**Comment by killwort** [comment]
I've never tried to do something like that. Probably DataTable.Load depends on schema introspection, and clickhouse is inferior in that area.
