### ISSUE TITLE
Пул подключений к БД

### ISSUE THREAD

**Issue by madmax46** [killwort/ClickHouse-Net#160]
Не хватает функционала пула подключений к базе. Ведь создавать на каждый коннект TcpClient, затем после использования коннекта закрывать этот TcpClient выглядит ресурсоемким процессом. Планируется ли добавить в библиотеку пул подключений к базе?

**Comment by killwort** [comment]
Внутри библиотеки пул соединений я делать не планировал. При необходимости можно пользоваться обычным ObjectPool, но мне эта идея не кажется очень хорошей, так как протокол не обладает свойством самосинхронизации и ошибки возникшие при каких-то нарушения в одном соединении распространятся на следующее использование из пула.
В принципе, сценарии использования clickhouse не предполагают высокой частоты чтения (редкие OLAP запросы с длительным выполнением) или записи (запись должна буферизовываться и даже в документации clickhouse не рекомендуют делать больше одного insert в секунду), поэтому экономия на времени установки TCP и даже TCP+TLS соединения кажется не нужной. Если ваши сценарии предполагают более частые запросы, возможно стоит посмотреть в сторону [HTTP протокола, где можно пользоваться keep-alive или HTTP/2](https://clickhouse.com/docs/en/interfaces/http) или даже [HTTP/2+gRPC](https://clickhouse.com/docs/en/interfaces/grpc)
