### ISSUE TITLE
ClickHouseConnection how to use it properly

### ISSUE THREAD

**Issue by PyatiyEtaj** [killwort/ClickHouse-Net#163]
## Description
Hi, Just want to understand how to properly use `ClickHouseConnection`
1. Should each request use its own `ClickHouseConnection`?
2. Can i create a pool with ready-to-use connections?

Because There are some issue
1. I think it is long operation and each connection creates it's own TcpClient. This leads to Socket exhaustion or am i wrong
2. Maybe there is a dead lock problem in case of exception during query.

## Steps to reproduce
A `DataAccessException` exception occurred during the request. After that, all queries using this connection are blocked. If you close the connection and reopen it, it will also be blocked.
```cs
await connection.OpenAsync();
```

**Comment by killwort** [comment]
1. I usually use one connection per command. Yes, there's overhead for opening socket/TLS connection however if you follow clickhouse own guidelines (do not use CH as OLTP database, do bulk inserts, do OLAP queries) it is OK and probably neglectible.
2. You could definetely use ObjectPool for connections however.
The clickhouse native protocol does not have any self-synchronization ability, so any error will lead to undefined behavior for any subsequent communications on the given connection. So in my opinion you should wrap all clickhouse operations into some retry cycles, and if any exception is thrown it is a clear sign that you should dispose active connection and open a new one.
