### ISSUE TITLE
how to get correct value from datetime64 ?

### ISSUE THREAD

**Issue by xibaoning** [killwort/ClickHouse-Net#164]
ClickHouse server version 24.2.2

SELECT toDateTime64('2022-06-24 14:00:00.001', 3, 'Asia/Shanghai')
┌─toDateTime64('2022-06-24 14:00:00.001', 3, 'Asia/Shanghai')─┐
│                                     2022-06-24 14:00:00.001 │

``` C#
//ClickHouse.Ado 2.0.3

using var cmd = conn.CreateCommand($"select toDateTime64('2022-06-24 14:00:00.001', 3, 'Asia/Shanghai')");
using var reader = cmd.ExecuteReader();
if (reader.NextResult())
{
    if (reader.Read())
    {
		var timestr = reader.GetDateTime(0).ToLocalTime().ToString("yyyy-MM-dd HH:mm:ss.fff.ffffff");
		//timestr result = "2022-06-24 14:00:00.000.000999"  why ?
		//how to get correct value : "2022-06-24 14:00:00.001"  ?
    }
}
```

**Comment by killwort** [comment]
Because it uses floating point math to get from integer number of `precision` time intervals to `double` seconds difference to unix epoch.
In other words, it is ok to have that result. If you know exactly what precision it shoud be, you could round to that precision.
