### ISSUE TITLE
Special Character and connect string requirements

### ISSUE THREAD

**Issue by flutos** [killwort/ClickHouse-Net#167]
1. I found a couple issues regarding using the special characters : and @ in a sql statement
    if you execute a statement like this : CREATE USER if not exists "MYDB" identified by 'Repo@here:there';
    This will generate this error:
    Error  : System.InvalidOperationException: Sequence contains no matching element
    Detailed exception info:
    Source: System.Linq
 
   The reason is its thinking the @ and : are substitutions parameters so its trying to do substitutions
 
   I found the simplest work around is to modify the CLickHouseCommand.SubstituteParaemters()  and add a check for Parameters.Count. if there are no parameters then don't bother trying to do the substitution.

2. for the Click house connect strings , they need to be Camel Cased. Ie , BatchSize=...;User= ...;Password=... 
     If they are not camel cased to match whats in the class ClickHouseCOnnectionSettings then you will get the error: The given key 'xyz' was not present in the dictionary. 
 
     The simplest work around was to change the ClickHouseConnectionSettings.Properties to store the property keys  as all upper case or lower case and look for them in the same way . Doing that will make it so you dont have to have the connect string keys match the camel case structure of that class.

We have a work around to to allow : or @ and to educate the end user to follow camel case syntax but it can be a little much to expect from an end user.

**Comment by killwort** [comment]
1. You should never use string literals for input, it will lead you to SQL-injection hell. Use parameter instead.
2. I never saw it as a problem but surely I could fix that.
