### ISSUE TITLE
Problem with query_log

### ISSUE THREAD

**Issue by Saturma** [killwort/ClickHouse-Net#17]
I think that there is a problema in queries. When I execute a query with this API I didn´t found it in system.query_log table. 

I execute the same queries with the same user with Tabix or with clickhouse-client and they appears. But when I execute it with this wrapper they don´t.

**Comment by killwort** [comment]
CH server documentation states that queries are logged when they run with log_queries settings. My client does not export per-query settings in public API, however support for them is implemented and you could easily alter this behavior by modifying _clickHouseConnection.Formatter.RunQuery call in ClickHouseCommand.Execute.
If you decide to implement this functionality, please fork and do pull request afterwards.
