### ISSUE TITLE
No rows returned in select statement, though data is present in the table

### ISSUE THREAD

**Issue by pmsudhi** [killwort/ClickHouse-Net#172]
## Description
I have a click house table containing 85k rows. when I select a statement in clickhouse consol, it returns the data. but when I execute this using a data reader, the HasRows functions return false.

## Steps to reproduce
1. Connect to Clickhouse DB
`            var connectionString1 = "Host=myclickhouse.aws.clickhouse.cloud;Port=9440;Database=My_DB;User=default;Password=MyPassword;Encrypt=true;";

   var connection = new ClickHouseConnection(connectionString1);

   connection.Open();

 ClickHouseCommand command = connection.CreateCommand("SELECT * FROM MyTable");

 command.Connection = connection;

 var dr = command.ExecuteReader();
`

the dr has the correct field count information but does not return any rows

**Comment by killwort** [comment]
Well, most probably you're not using NextResult. Please read the documentation.
That kind of queries (projections=*, no where, no group, no order) are most prone to giving multiple resultsets.
