### ISSUE TITLE
changing output parameter value

### ISSUE THREAD

**Issue by gustavo-campos** [killwort/ClickHouse-Net#174]
I have a command with an output parameter and I want to change its value in the command.

command.Parameters.Add(new ClickHouseParameter()
{
ParameterName = "TEST",
DbType = System.Data.DbType.String,
Direction = System.Data.ParameterDirection.InputOutput,
Value = "1",
Size = -1
});
command.Connection = chConnection;
command.ExecuteNonQuery();

commands that were tested

SET :TEST = "2";
Select :TEST As Ok;

What is happening is a replacement of the content :TEST for the passed value and it is not creating a variable where I can change its value, how can I do this, is there anything that can help me?

**Comment by killwort** [comment]
Clickhouse does not support parameters in commands natively, so they are implemented on driver level and cannot be 'output' parameters. Additionally clickhouse does not support user variables (is that what are you trying to do?), SET statemnents are used exclusively for manipulating clickhouse settings and not for arbitrary variables.
