### ISSUE TITLE
Posible Error with DISTINCT

### ISSUE THREAD

**Issue by Saturma** [killwort/ClickHouse-Net#20]
I don't know if is a Error of ClickHouse.Ado or not. I have a simple distributed table  and I do a a Simple query: 

"SELECT COUNT ( DISTINCT  campo) AS cnt FROM BBDD.Tabla
WHERE InsertionDate >= today()"

I receive a TimeOut when I do the "reader.NextResult()". I receive a Exception: 
_"Connection reset by peer while writing to socket"

"   en System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   en ClickHouse.Ado.Impl.UnclosableStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   en ClickHouse.Ado.Impl.ProtocolFormatter.ReadBytes(Int32 i)    
   en ClickHouse.Ado.Impl.ProtocolFormatter.ReadByte()    
   en ClickHouse.Ado.Impl.ProtocolFormatter.ReadUInt()   
   en ClickHouse.Ado.Impl.ProtocolFormatter.ReadPacket(Response rv)   
   en ClickHouse.Ado.Impl.ProtocolFormatter.ReadBlock()   
  en ClickHouse.Ado.ClickHouseDataReader.NextResult()   
  en CHB_BackTestingConsole.ClickHouse.RunQuery(String query, List`1 l_header, List`1 l_types)  "_

If I do the same query, but without the "DISTINCT", it works perfectly. 
"SELECT COUNT ( campo) AS cnt FROM BBDD.Tabla
WHERE InsertionDate >= today()"

I proved the same query with other  Python APIS, sqlAlchemy, Tabix, etc... and It works perfectly.
I proved changing conexion parameters, without succeed:
                ConnectionTimeout=2000;
                SocketTimeout=1000;
                DataTransferTimeout=100000;

Any Ideas?? Could it be a bug in your code?? Or Maybe in the Native Driver??

Thanks.

**Comment by killwort** [comment]
Most probably there's some desync in protocol. Please provide SQL CREATE for your table and clickhouse server version number, I'l try to reproduce and fix it. However error might be related to the data you store inside table so complete dump will help.

As a workaround you can try disabling compression

**Comment by killwort** [comment]
I think this is not a socket/connection problem. Driver times out on Read, so it must be reading something while server didn't send anything.

**Comment by killwort** [comment]
I cannot do anything about it without stable reproduction. Closing for now.
