### ISSUE TITLE
ChunkedStream

### ISSUE THREAD

**Issue by volframka** [killwort/ClickHouse-Net#21]
Добрый день

Я не могу даже собрать Ваш проект.

1) Я его скачал, распаковал.
2) Запускаю ClickHouse.sln в VisualStudio 2017.
3) Компилирую, ошибка:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'ChunkedStream' could not be found (are you missing a using directive or an assembly reference?)	ClickHouse.Ado	D:\Work\\ClickHouse-Net-master\ClickHouse.Ado\Impl\Compress\HashingCompressor.cs	34	Active

Может быть, есть где-то хитрая инструкция по сборке?

**Comment by killwort** [comment]
Готовые сборки есть в nuget, поиск по слову clickhouse находит.
Я собираю VS 2017 Preview (15.6.0). Солюшн и проект без суффикса netstandard вообще очень старые и их не надо пытаться собирать. Свежие - те что с netstandard, и они собирают для всех целевых платформ.

**Comment by volframka** [comment]
К сожалению, этот проект у меня так же не собирается...
Severity	Code	Description	Project	File	Line	Suppression State
Error		Assets file 'D:\Work\TFS\FORIS_Mobile\TeamWork\CM_Team\Dev\Projects\ClickHouseClient\ClickHouseClient\ClickHouse-Net-master\ClickHouse.Ado\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	ClickHouse.Ado.NETStandard	C:\Program Files\dotnet\sdk\2.0.3\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	323

**Comment by killwort** [comment]
Наверно надо выполнить 
`dotnet restore`
или
`nuget restore`

Обычно студия это делает сама.
Кроме того, можно попробовать собрать из командной строки 
`dotnet build`
