### ISSUE TITLE
Type mismatch for Enum8 

### ISSUE THREAD

**Issue by DmitryDem** [killwort/ClickHouse-Net#23]
![clip2net_180507222650](https://user-images.githubusercontent.com/5823289/39720658-ccfda752-5245-11e8-8e80-cf7b9d6465d3.png)

There is error in the following code. The escape of string for the enum value is excess:
public override string AsClickHouseType()
        {
            return $"Enum{BaseSize}({string.Join(",", Values.Select(x => $"{**ProtocolFormatter.EscapeStringValu**e(x.Item1)}={x.Item2}"))})";
        }

**Comment by killwort** [comment]
Thanks for your PR!
