### ISSUE TITLE
Bad message type 53 received from server.

### ISSUE THREAD

**Issue by vytu** [killwort/ClickHouse-Net#25]
My code <br>
`
      string cstr = "Compress=True;CheckCompressedHash=False;Compressor=lz4;Host=192.168.7.34;Port=22;Database=default;User=root;Password=111";`<br>
      `var settings = new ClickHouseConnectionSettings(cstr);`<br>
      `var cnn = new ClickHouseConnection(settings);`<br>
     ` cnn.Open();`
<br>
But I receive error:<br>
`Bad message type 53 received from server.`<br>
What means code 53?

**Comment by xontab** [comment]
Looks like this was caused during handshake. Which version of ClickHouse are you using?  Can you use the default port 9000?

**Comment by killwort** [comment]
Either it is new clickhouse server version which I do not support (yet) or there's some protocol desync.
First of all try disabling compression - it is notorious for causing similar troubles due to slight differences in .net and c++ implementations.

**Comment by killwort** [comment]
Message code 53 is simply the type of message server sends in each packet header. It has no other special meaning. However for a long time clickhouse used these types <=8, so getting 53 here most probably means protocol desync.

**Comment by killwort** [comment]
I've reproduced this bug and it seems that it is not a bug at all :)
By default my driver uses TCP buffer of size 1024 - exactly the same that can be seen in CH's sources (at least in older versions) and despite that server sends bigger packets (in my case 1500+ bytes). This causes data loss upon receive and infinite waits upon consequent receives.

Bottom line: 
To quickly fix without new binary version just set BufferSize=8192 (or whatever value you see reasonable) in your connection string.
Moreover, I'm changing default 1024 ripped from CH sources to 4096 as it definetaly has more sense.

**Comment by MagierCapo** [comment]
Although this issue has closed ...
I expierence the same error "Bad message type 53 received from server"

My ConnString is "Host=localhost;Port=8123;User=default;Password=;BufferSize=8192;"
where I had to SSH-tunnel the Port 8123 to the remoteServer

There is installed  ClickHouse server version 19.7.3 revision 54419

Might be that there is an issue with this ClickHouse-Version, how  commented on 21 Jun 2018 ?

**Comment by MagierCapo** [comment]
Although this issue has closed ...
I expierence the same error "Bad message type 53 received from server"

My ConnString is "Host=localhost;Port=8123;User=default;Password=;BufferSize=8192;"
(I had to SSH-tunnel the Port 8123 to the remoteServer)

There is installed  ClickHouse server version 19.7.3 revision 54419
Might be that there is an issue with this ClickHouse-Version, how  commented on 21 Jun 2018 ?
