### ISSUE TITLE
 problem working with datetime on clickhouse-server and clickhouse.ado

### ISSUE THREAD

**Issue by uottoni** [killwort/ClickHouse-Net#30]
I have a problem working with datetime on clickhouse-server and clickhouse.ado.
When I perform a insert with a datetime from remote app with clickhouse.ado, and then use a select with the datetime columm, the server returns the datetime without the timezone offset.
If I execute the select command from server machine using clickhouse-client, the server returns datetime correctly( with my timezone offset).
Ex.:
The same query: SELECT toDateTime('2018-07-20 :11:55:00')
return from clickhouse-client directly on server: 2018-07-20 11:55:00
return from remote app with clickhouse.ado: 2018-07-20 14:55:00

For replication proporses:
My timezone: America/Sao_Paulo (-3 hours)
Debian server version: 9.4
.NET Framework version on remote app: 4.6.1
clickhouse-server version: 1.1.54394 and 1.1.54383 (same result on both versions)
clickhouse.ado version: 1.1.9

Thanks, Ulisses Ottoni
P.S.: Sorry my bad english

**Comment by ste-art** [comment]
Same issue with parameterized queries:
```C#
using (var command = connection.CreateCommand())
{
	command.CommandText = "CREATE TABLE IF NOT EXISTS TimeTest (Time DateTime, Date Date MATERIALIZED toDate(Time)) ENGINE MergeTree(Date, Time, 8192)";
	command.ExecuteNonQuery();
}

var now = DateTime.UtcNow;

using (var command = connection.CreateCommand())
{
	command.CommandText = "INSERT INTO TimeTest (Time) VALUES (@Time)";
	command.AddParameter("Time", DbType.DateTime, now);
	command.ExecuteNonQuery();
}

using (var command = connection.CreateCommand())
{
	command.CommandText = "SELECT COUNT(*) FROM TimeTest WHERE Time = @Time";
	command.AddParameter("Time", DbType.DateTime, now); // Same time as in INSERT.
	var count = command.ExecuteScalar();
	Console.WriteLine(count); // Always 0. Nothing found.
}

// It only works if the time is INSERT'ed as UTC,
// But in SELECT the parameter is converted to local time.
var localTime = now.ToLocalTime();
using (var command = connection.CreateCommand())
{
	command.CommandText = "SELECT COUNT(*) FROM TimeTest WHERE Time = @Time";
	command.AddParameter("Time", DbType.DateTime, localTime);
	var count = command.ExecuteScalar();
	Console.WriteLine(count); // Now it's 1.
}

```

**Comment by killwort** [comment]
Timezone support was introduced into clickhouse in 1.1.54337 of 2018-01-18. I cannot say whether they changed binary protocol however in the version I support datetimes are internaly represented by unixtimes (number of seconds passed from unix epoch start 1970-01-01 00:00:00) - without any mentions of zone offset or something like that. So timezones are supported by CH SQL and not by named parameters (they're substituted with AssumeUtc) nor by fetching data back from CH (binary protocol limitation).

IMHO you should always store datetimes in UTC and, if you really need to, add separate column with tz offset. If you'd like to perform selects on client-tz adjusted days you'd probably pre-add tz offset to your values - that would save on computation during select operations.
