### ISSUE TITLE
Can this SDK support Json or not?

### ISSUE THREAD

**Issue by TianyiLu** [killwort/ClickHouse-Net#33]
I want to use JsonEachRow while inserting or querying, is there any support on Json ? and how can I set the parameters type?

ClickHouseParameter parameter = new ClickHouseParameter
            {
                DbType = DbType.Object,
                ParameterName = "bulk",
                Value = list.SafeSelect(x => x.JsonSerialize()).ToArray()
            };

**Comment by TianyiLu** [comment]
Thanks for your reply.
So, is there any SDK support JsonEachRow insertion? I can try to switch my implementation to other language.

**Comment by killwort** [comment]
Cannot say for sure. Most probably you could try any HTTP-based SDK (java, php, etc. - all SDKs except mine and CH's native C SDK utilize HTTP protocol) - they should support new features almost immediately due to the nature of the transport protocol.
