### ISSUE TITLE
Failing to connect (at handshake stage) to Hosted ClickHouse cluster

### ISSUE THREAD

**Issue by AndreyTsvetkov** [killwort/ClickHouse-Net#36]
## Description
I have run into a connection issue while trying to work with ClickHouse via this API:

```
			var connectionString = $"Compress=True;CheckCompressedHash=False;Compressor=lz4;Host={_opts.Host};Port={_opts.Port};Database={_opts.Database};User={_opts.User};Password={_opts.Password}";
			var settings = new ClickHouseConnectionSettings(connectionString);
			var connection = new ClickHouseConnection(settings);
			connection.Open();

```
Here the exception is raised `SocketException: An existing connection was forcibly closed by the remote host`. 

After come digging, I've discovered, that it is in the middle of the handshake process, right after sending client name ("ClickHouse .NET client library")

![image](https://user-images.githubusercontent.com/2841760/47308897-a259aa80-d63b-11e8-8224-71d9539da78b.png)

**Comment by alexey-milovidov** [comment]
Do you connect to TLS-enabled (secure) port of the hosted ClickHouse cluster?

**Comment by killwort** [comment]
I'll try to implement TLS wrapping sometime later :)
Yet it is really not top priority.
