### ISSUE TITLE
Hi! I ran into a trivial problem. I can't find how to send a single set of data using the insert statement. How to do it? The example in README does not work for me.

### ISSUE THREAD

**Issue by Samue1G** [killwort/ClickHouse-Net#38]
## Description
... provide some general description of what has gone wrong or what you're proposing ...

## Steps to reproduce
1. You should include database structure as one of the steps (just CREATE commands you user to create relevant tables and some data suitable for test)
1. The second most important thing is SQL commands you run through the driver that gives trouble
1. And lastly, you could include some code that reproduces error
1. Anyway you may not follow these steps if you feel they're not relevant to your issue

## Workarounds
... if you know some workaround for the issue, provide it here ...

## What should be done
... if you know what should be done to mitigate the issue, provide it here ...

**Comment by killwort** [comment]
I do not fully understand what are you trying to do, but you could use two syntaxes to insert one row:
1. Normal SQL INSERT with values, e.g. `INSERT INTO table (columns) VALUES (@value-params)`
1. Bulk insert with one row in list, e.g. `INSERT INTO table (columns) VALUES @bulk)

Either way is discouraged by clickhouse documentation, you should really consider accumulating inserted data until you have at least several dozens of rows.
