### ISSUE TITLE
Lz4

### ISSUE THREAD

**Issue by thyn** [killwort/ClickHouse-Net#39]
I'm having problem with library you are using. The author suggested to use new port of lz4. Is it possible to fix?

Details are here

https://github.com/MiloszKrajewski/lz4net/issues/38

**Comment by killwort** [comment]
I've tried a couple of LZ4 implementations before coming to lz4net, and they were incompatible with the one used in CH server. I'd give some new libs a try when I decide to do a full rewrite using different approaches yet there's no ETA for it.
