### ISSUE TITLE
SELECT ... WHERE Id IN @bulk

### ISSUE THREAD

**Issue by podkolzzzin** [killwort/ClickHouse-Net#44]
## Description
It would be really cool to have chance to use bulk parameters(Enumerables) for parameters in "IN clause"

**Comment by killwort** [comment]
You actually can!
`            using (var cmd = cnn.CreateCommand("SELECT * FROM `test_data` WHERE user_id IN (@values)"))
            {
                cmd.Parameters.Add("values", DbType.UInt64, new[] {1L, 2L, 3L});
                using (var reader = cmd.ExecuteReader())
                {
......
                }
            }
`
