### ISSUE TITLE
Problem with 1.1.10 release

### ISSUE THREAD

**Issue by VitaliyMF** [killwort/ClickHouse-Net#47]
I tried to upgrade to latest ClickHouse.Ado 1.1.10 nuget package but for some reason it doesn't work for me. I execute queries and iterate through results with data reader; I able to read all rows, but then my thread is blocked with either data reader dispose or connection close (still not sure what exactly blocks execution). Just to note, this is NET Core 2.1 app.

Version 1.1.9 works fine with the same queries; as I see by commits only significant change is usage of `BufferedStream` #46, so maybe it is related to this issue.

**Comment by killwort** [comment]
I'm seeing this issue too especially when running queries in parallel. v.1.1.12 is broken in the same way.
I will release 1.1.13 with rolled back BufferedStream - anyway there were no performance gain in using it.

**Comment by VitaliyMF** [comment]
> anyway there were no performance gain in using it

I've the same observation. Only parameter that significantly affects performance in case of large resultsets is 'BufferSize' for TcpClient, with value = 8k-16k ClickHouse.Ado works pretty fast.
