### ISSUE TITLE
Problem in INSERT from file

### ISSUE THREAD

**Issue by chiragjindal** [killwort/ClickHouse-Net#48]
I recently started using Clickhouse and planning to migrate data to use via this interface. 
I have a requirement to insert millions of rows of data from a text file present on HDFS or Azure storage.
I don't find any solution to resolve this. I need a functionality similar to SQL bulk insert, for a file present on external storage. Let me know if I can get some help towards this.

**Comment by killwort** [comment]
To do import/export it is better to use clickhouse command line client. It will be far more effective.
