### ISSUE TITLE
Possible infinite cycle in ProtocolFormatter

### ISSUE THREAD

**Issue by VitaliyMF** [killwort/ClickHouse-Net#5]
In my  usage scenario ClickHouse select query can take some time, and SocketTimeout value used by default (1000 which means 1s) is too small; this value can be changed with connection string of course, but I have noticed strange thing: when timeout is reached (most likely) datareader falls into infinite cycle that never stops (and causes 100% CPU load of 1 core); I was able to reproduce this situation at least twice. 

I've reviewed the code, and it seems this is possible in ProtocolFormatter.ReadBytes method:

```
            do
            {
                read += _ioStream.Read(bytes, read, i - read);
            }
            while (read < i);
```
_ioStream (which is `NetworkStream` actually) can return 0 in case if underlying socket is closed (this is mentioned in the documentation for "NetworkStream.Read" method). It seems when timeout is reached socket is closed so thing might be a reason of the infinite cycle.

My propositions:

- increase default value for SocketTimeout to at least 60000 (60 sec)
- change "ReadBytes" code to handle zero-read result. Should it throw an exception? I don't know much about ClickHouse binary protocol.

**Comment by VitaliyMF** [comment]
Update: I forgot that it is normal for NetworkStream to return 0 for Read method if buffer is empty and we just wait for the data. I've changed ReadBytes in the following way:

```
            var networkStream = _ioStream as System.Net.Sockets.NetworkStream;
            do
            {    				
                cur = _ioStream.Read(bytes, read, i - read);
                read += cur;
                if (cur==0) {
                    // check for DataAvailable forces an exception if socket is closed
                    if (networkStream!=null && networkStream.DataAvailable) 
                        continue;
                    System.Threading.Thread.Sleep(1);
                }
            }
            while (read < i);
```

1. this code prevents 100% CPU core load if "Read" returns 0 many times
2. check for DataAvailable should deal with closed socket

@killwort what do you think on this?

**Comment by killwort** [comment]
I've used your solution for this problem however I've never reproduced this situation,
Nuget package received an update too; move to v.1.0.1.

**Comment by VitaliyMF** [comment]
@killwort thanks! JFYI, I also wasn't able to reproduce 100% CPU load in my dev env (win7 + netcore1.1); this situation was detected only on production server (ubuntu server 16.04 + netcore1.1).
I hope this patch will help; if not I'll come back with new details.

**Comment by killwort** [comment]
This may be caused by different network stack implementation in Linux. I recall that I had some similar problems when I was developing for mono.
