### ISSUE TITLE
ClickHouseCommand.ExecuteReader throws NotSupportedException when used with Dapper

### ISSUE THREAD

**Issue by dorzhevsky** [killwort/ClickHouse-Net#53]
## Description
I'm trying to integrate ClickHouse.NET with Dapper. When I invoked ExecuteReader method NotSupportedException has been thrown. IMHO that is ClickHouse.NET issue rather than Dapper problem.

## Steps to reproduce
1. Create "persons" table in ClickHouse
CREATE TABLE persons (inn String, name String, pass String) ENGINE=MergeTree() ORDER BY inn
2. Create .NET project targeting .NET 4.5
3. Install ClickHouse.NET and Dapper NuGet packages
4. Create Person class
    class Person
    {
        public string inn { get; set; }
        public string name { get; set; }
        public string pass { get; set; }
    }
5. Run the following code 
    using (var cnn = GetConnection())
    {
         var r = cnn.QueryMultiple(@"SELECT * FROM persons ORDER BY inn");
         List<Person> result = new List<Person>();
         while (!r.IsConsumed)
         {
              var list = r.Read<Person>();
              result.AddRange(list);
         }
     }

I think this issue is somehow related to https://github.com/StackExchange/Dapper/issues/441

## What should be done
I suggest to just remove the following code from ExecuteReader method
`
   if ((behavior & (CommandBehavior.SchemaOnly | CommandBehavior.KeyInfo | CommandBehavior.SingleResult | 
CommandBehavior.SingleRow |
 CommandBehavior.SequentialAccess)) != 0)
  throw new NotSupportedException($"CommandBehavior {behavior} is not supported.");
`

**Comment by killwort** [comment]
I've removed CommandBehavior checks completely as you suggested. 
Yet, Dapper may not work 'cause clickhouse disregards SingleResult flag.
