### ISSUE TITLE
GUID to UUID type convertation problem

### ISSUE THREAD

**Issue by licicego** [killwort/ClickHouse-Net#57]
## Description
When inserting records containing a GUID, an incorrect conversion occurs.
As a result, the table contains a value that does not match the transmitted one.

## Steps to reproduce
1. The TestTable table was created for testing. 
> CREATE TABLE tflow.TestTable (
> `GlobalUID` UUID,
> `Name` String
> ) ENGINE = ReplacingMergeTree() ORDER BY (GlobalUID, Name) SETTINGS index_granularity = > 32768
2. A test application has been created.

            var testConnection = new  ClickHouseConnection(_connString_);

            var list = new List<TestTable>();

            list.Add(new TestTable()
            {
                GlobalUID = Guid.Parse("dca0e161-9503-41a1-9de2-18528bfffe88"),
                Name = "Example 1"
            });

            var commandBulkInsert = testConnection.CreateCommand();
            commandBulkInsert.CommandText = "INSERT INTO TestTable (GlobalUID,Name) VALUES @bulk";
            commandBulkInsert.Parameters.Add(new ClickHouseParameter
            {
                ParameterName = "bulk",
                Value = list
            });

            testConnection.Open();
            commandBulkInsert.ExecuteNonQuery();
            testConnection.Close();

TestTable.cs

    public class TestTable : IEnumerable
    {
        public Guid GlobalUID { get; set; }
        public string Name { get; set; }

        public IEnumerator GetEnumerator()
        {
            yield return GlobalUID;
            yield return Name;
        }
    }

3. For example, the same GUID was inserted using DBeaver. SQL:
`INSERT INTO TestTable VALUES (toUUID('dca0e161-9503-41a1-9de2-18528bfffe88'),'Example 2')`
4. Query result
`SELECT * FROM TestTable`

> GlobalUID                           |Name     |
> ------------------------------------|---------|
> 41a19503-dca0-e161-88fe-ff8b5218e29d|Example 1|
> dca0e161-9503-41a1-9de2-18528bfffe88|Example 2|

## Conclusion
As can be seen from the test, when using ClickHouse-Net, when inserting a specific value (**dca0e161-9503-41a1-9de2-18528bfffe88**), a completely different one is entered into the database (**41a19503-dca0-e161-88fe-ff8b5218e29d**)

**Comment by killwort** [comment]
Its not different yet it has different byte order. That's still a bug! Thanks.

**Comment by killwort** [comment]
More to that, guid reading was also made with incorrect byte order resulting in mangled guids on read after write.
I've fixed GuidColumnType to read/write Guids in clickhouse's (incorrect) byte order, so now you can mix Clickhouse.ADO writing with reading via another methods.

**Comment by killwort** [comment]
nuget v.1.1.17.
