### ISSUE TITLE
ClickHouseDataReader.GetFieldType returns type of internal class instead of value type

### ISSUE THREAD

**Issue by VitaliyMF** [killwort/ClickHouse-Net#6]
It seems `ClickHouseDataReader.GetFieldType` works incorrectly; it returns type of the internal class that represents ClickHouse type (like 'ClickHouse.Ado.Impl.ColumnTypes.SimpleColumnType`1[System.Byte]') instead of real .NET value type. These classes are internal and this type is useless.

**Comment by killwort** [comment]
Added internal CLRType to ColumnType and returning it upon GetFieldType calls.
Assembly/file version and nuget package updated to 1.0.2
