### ISSUE TITLE
What should I write connection string for the cluster clickhouse ?

### ISSUE THREAD

**Issue by zhaobingwang** [killwort/ClickHouse-Net#60]
What should I write connection string for the cluster clickhouse ?
In my test server(only one clickhouse),the connectionStrings is below,it works fine.
 ```
 <connectionStrings>
    <add name="ck.conn" connectionString="Compress=True;CheckCompressedHash=False;Compressor=lz4;Host=192.168.2.10;Port=9000;Database=test;User=default;Password=" />
  </connectionStrings>
```
but i have no idea how to write connection string for the cluster clickhouse ? any idea?

**Comment by killwort** [comment]
You should properly do load balancing and specify load balancer in server. Easiest way - make DNS A/AAAA records for each of your clickhouse hosts with the same name and specify that name in connection string. DNS round-robin will choose new address from pool for each new connection.

By the way, you may use one address for connections and clickhouse will properly distribute queries/load among all hosts in cluster.
