### ISSUE TITLE
Sum(DecimalField) length is not correct

### ISSUE THREAD

**Issue by MortenVittrupGade** [killwort/ClickHouse-Net#65]
## Description
When having a decimal field specified as Decimal(9,2), its fails when receiving a sum:
1) Select anotherColumn,DecimalColumn from Table: **OK!**
2) Select anotherColumn,Sum(DecimalColumn) from Table group by anotherColumn: **Fails!**

## Steps to reproduce
1) Create Table B (Id UInt16, Money Decimal(9,2)) Engine = Log
2) insert into B values (1,3.14);
3) Query: SELECT Id,Money from B => **OK**
4) Query: SELECT Id,Sum(Money) from B group by Id => **Fails**  (Expected same result as above)

![image](https://user-images.githubusercontent.com/7657721/64068897-5f933680-cc3f-11e9-88d0-50adc7b91550.png)

## Workarounds
I would like to hear some ;)

**Comment by killwort** [comment]
As it is said in the exception message: there's a limit on decimal precision in CLR.
You can use toDecimal32/toDecimal64/toDecimal128 functions to cast aggregated sum to decimals representable in CLR.
