### ISSUE TITLE
Slow NextResult when large dataset

### ISSUE THREAD

**Issue by MortenVittrupGade** [killwort/ClickHouse-Net#66]
## Description
If you return a relatively large result set from Clickhouse (like 25k rows) it takes ~10 secs for the reader to do what it needs to do.
The query it self takes 300 ms in clickhouse, but before the response is returned it takes 10 sec. I have tried to make the same call in a bash console, and the result is instant (Even thogh piping this result to a webservice). This also across machines to verify that that its not an network issue.

So I'm quite sure the error is in the .NET implementation. in the NextResult command.

**Comment by VitaliyMF** [comment]
Have you tried to increase TCP buffer size? Something like `BufferSize=16384` in the connection string.

**Comment by killwort** [comment]
I know that current implementation is very inefficient for large datasets yet I cannot do anything about that now (there's much copying/converting data to adapt clickhouse's column orientired protocol to row-based ADO interfaces).
I have plan for major rewrite using System.IO.Pipelines, hope I'll have enough time for it this year :)

**Comment by killwort** [comment]
And as a rule of thumb, aggregate data on clickhouse side, anyway clickhouse is designed to be OLAP database. 
Although I use clickhouse as a log storage (that means append-only non-aggregable dataset) yet I've never noticed any performance issues on SELECTs - primarily due to paged output on client side.

**Comment by xiaomuwing** [comment]
a very simple INSERT also take more than 40 ms on local server, which only take 0.001ms on clickhouse-client......

**Comment by killwort** [comment]
¯\(°_o)/¯
