### ISSUE TITLE
Strange incompatibilities in build for netstandard1.1

### ISSUE THREAD

**Issue by VitaliyMF** [killwort/ClickHouse-Net#7]
Andrey,

My netcore1.0 app which reference netstandard1.5 build of ClickHouse.Ado.
Recently I've switched to netcore1.1 target that starts using build that targets "netcore1.1" and for some reason this build is quite different from net451 / netstandard1.5:  for example, ClickHouseConnection doesn't implement IDbConnection and ClickHouseDataReader doesn't implement IDataReader (??).

Could you explain 
1) why special "netcore1.1" build is needed at all (netstandard1.5 can be referenced by wide variety of platforms including both netcore1.0 and netcore1.1
2) why "netcore1.1" doesn't implement standard ADO.NET interfaces (this is really weird)

**Comment by killwort** [comment]
1. I've made netcoreapp1.1 target especially for minimal runtime dependencies. Actually it depends only on lz4 (this is also removable) and system.threading.thread apart from netcoreapp  If you plan to use this lib in full environment, please, use netstd build.
2. 'Cause it doesn't reference ADO.NET libs. See 1 for explanation.

Just to be clear: do not use netcoreapp target at all, use netstd instead.

Maybe in the future I'll split netcoreapp into separate branch or something like that but for now I'm quite content with current structure. Feel free to propose any other structure as I'm new to multitarget projects.

**Comment by VitaliyMF** [comment]
Andrey,
it seems it is not possible to force usage of netstandard1.5 build if netcore1.1 build exits from project that targets netcore1.1. Of course netstandard1.5 can be used in this case (and this is strange why special incompatible build for netcore1.1 exists at all).

**Comment by killwort** [comment]
Well, in my case netcoreapp project references netcoreapp build.
And when I need netstd build, my netcoreapp project references internal netstd lib which references netstd clickhouse build.

**Comment by killwort** [comment]
OK, let's merge netstd and netcoreapp as it causes too much trouble. I'm adding system.data.common as a dependency fro netcoreapp build, and replacing #define NETCOREAPP11 with NETSTANDARD15

**Comment by VitaliyMF** [comment]
Possibly I've missed something, could you let me know how to force netstandard build usage with <PackageReference> tag (in csproj) ?

**Comment by VitaliyMF** [comment]
> I'm adding system.data.common as a dependency fro netcoreapp build, and replacing #define NETCOREAPP11 with NETSTANDARD15

possibly NETCOREAPP11 target is not needed at all. Concept of netstandard target specially was introduced by MS for targeting many platforms at once.

**Comment by killwort** [comment]
Imagine this reference graph
My project (netcoreapp) -> My data abstraction lib (netstd) -> Clickhouse.Ado (netstd).

In fact netstd is enforced for class library type projects, and netstd was just hacked into csproj by manual editing.
And netcoreapp is special target which is in fact netstd with different default dependencies used for directly executable projects (web apps+desktop apps). Despite that they're still has .dll extension and run with dotnet.exe.

**Comment by killwort** [comment]
I've pushed v.1.1.1 to nuget and here with compatible targets.

**Comment by VitaliyMF** [comment]
Andrey,
latest nuget package is still very strange. You have the following targets in .csproj:

`<TargetFrameworks>netstandard1.5;net451;netcoreapp1.1;net45;net40</TargetFrameworks>`

you can keep only:

`<TargetFrameworks>netstandard1.5;net40;net45</TargetFrameworks>`

as 'net451' and 'net45' builds define the same conditional compilation symbols.
However, 'netcoreapp1.1' prevents from correct usage of library because it is actually used in .NET Core 1 & 2 apps instead of netstandard1.5; this happens because you have removed ADO.NET interfaces for 'netcoreapp1.1' like:

```
#if !NETCOREAPP11
        :IDbCommand
#endif
```

This is weird as ADO.NET interfaces are available starting from .NET Core 1.0 and there are no any reason for this code.

**Comment by VitaliyMF** [comment]
@killwort maybe it's time to remove these conditionals for NETCOREAPP11 to avoid any confusion in future :-)
BTW, recently we switched to .NET Core 2 and provider works like a charm (it is used for SELECTs only with compression). Thank you!
