### ISSUE TITLE
System.InvalidCastException:“Unable to cast object of type 'System.Boolean' to type 'System.Byte'.”

### ISSUE THREAD

**Issue by 564064202** [killwort/ClickHouse-Net#71]
BulkInsert
ADO 1.20

**Comment by killwort** [comment]
Please, provide more context.

Probably you've tried to insert bool values directly into table - clickhouse does not support bool type. You have to do simple value conversion by yourself. E.g. instead of doing:
```
bool boolValue=true;
....
yield return boolValue;
```
do:
```
bool boolValue=true;
....
yield return (byte)(boolValue?1:0);
```
You could also write simple extension to hide ulgy ternaries :)
