### ISSUE TITLE
System.NotSupportedException: Unknown column type datetime

### ISSUE THREAD

**Issue by kayanme** [killwort/ClickHouse-Net#73]
## Description
Executing a simple query to a view with a datetime column throws  System.NotSupportedException
As I can see, it started after migration  from 17-version server to 20.

Maybe it's because of changed column type name case(DateTime->datetime).

**Comment by killwort** [comment]
I cannot find any signs of such behavior changes in clickhouse's documentation. Moreover, documentation exactly states the opposite:
https://clickhouse.yandex/docs/v20.1/en/query_language/syntax/#syntax-keywords

https://clickhouse.yandex/docs/v20.1/en/data_types/datetime/

Please provide more background for your issue.

**Comment by kayanme** [comment]
Changed column type in clickhouse was just an assumption, because nothing else have been changed for me. As you can see - the name in the exception message is in the lower case ("datetime"), and the key for column is "DateTime".
As an additional proof - my PR (where I get rid of case constraint for type name) fully solves the issue.

The use case for an issue is as described - any DataReader query execution I have to a view with a datetime column in clickhouse for docker "yandex/clickhouse-server:20.1.2.4" throws the exception I wrote.

**Comment by killwort** [comment]
I'll check that on clickhouse 20.1 in the coming weeks. For now I do not have that version at hand.

**Comment by killwort** [comment]
I was unable to reproduce that bug.
Installed clickhouse-server 20.1.2 revision 54431 from debian package.
Created table and view
```
create table test_dt20
(
    date Date,
    time DateTime,
    val String
)
engine MergeTree(date,(time), 8192);
create view test_dt20_view as select * from test_dt20;
insert into test_dt20(date,time,val)values(today(),now(), 'test');
```
And added the following test code:
```
        private ClickHouseConnection GetConnection(string cstr= "Compress=False;BufferSize=32768;SocketTimeout=10000;CheckCompressedHash=False;Compressor=lz4;Host=file-server;Port=9000;Database=default;User=test;Password=123")
        {
            var settings = new ClickHouseConnectionSettings(cstr);
            var cnn = new ClickHouseConnection(settings);
            cnn.Open();
            return cnn;
        }
        [Test]
        public void TestDateTimeInViewsV20() {
            using(var cnn = GetConnection())
            {
                var cmd = cnn.CreateCommand("select * from test_dt20_view");
                using (var reader = cmd.ExecuteReader()) {
                    reader.ReadAll(
                        r => {
                            var date=r.GetDateTime(0);
                            var dateTime = r.GetDateTime(1);
                            var val = r.GetString(2);
                            Console.WriteLine($"{date} {dateTime} {val}");
                        });
                }
            }
        }
```
It runs without any exceptions, printing out one row as expected.

**Comment by kayanme** [comment]
The type is datetime, like this:
```
create table if not exists DoubleTimeArchive 
     (tag String,time datetime CODEC (DoubleDelta), value Float64 CODEC (Gorilla), changeStamp  datetime CODEC (T64), sourceSink String,deletionFlag Int8 INDEX tag_index (tag) TYPE set(0) GRANULARITY 4 ) 
       ENGINE = MergeTree() PARTITION BY (toStartOfDay(time))  ORDER BY  (time,changeStamp);
```

**Comment by killwort** [comment]
There's a mismatch between actual behavior and the documentation. I've filed a ticket in CH's repository about that - https://github.com/ClickHouse/ClickHouse/issues/8962 
If devs say that case folding is OK, I'll accept your PR.

**Comment by killwort** [comment]
I've implemented it with type alias dictionary, so character case is folded only when it is required and not for all types. Nuget package will be ready soon.

**Comment by killwort** [comment]
Nuget v.1.1.21. https://www.nuget.org/packages/ClickHouse.Ado/1.1.21
