### ISSUE TITLE
how to use IBulkInsertEnumerable?

### ISSUE THREAD

**Issue by bibekdw** [killwort/ClickHouse-Net#75]
Hi,

Do you have any unit case or sample code on how to use IBulkInsertEnumerable during bulkinsert?

Thanks.

**Comment by killwort** [comment]
Check readme,
https://github.com/killwort/ClickHouse-Net#hidden-bulk-insert-functionality

**Comment by killwort** [comment]
Oh wait, you wanted to use `IBulkInsertEnumerable`? This is rather new/untested feature to avoid in-driver memory copying. It may improve performance for large inserts, to do so your @bulk parameter value must implement `IBulkInsertEnumerable`. If your implementation can effectively do `GetColumnData`, e.g. without scanning all rows to fetch one column for each row, it will reduce memory and CPU footprint. If your implementation scans rows, you'd probably don't need that, as commonly-used bulk inserts do exactly the same without any need to implement obscure interfaces.
