### ISSUE TITLE
the decimal bug

### ISSUE THREAD

**Issue by chenhunhun** [killwort/ClickHouse-Net#84]
## Description
if  i    insert into clickhouse by bulk mode.
...      private static void BulkInsert2()
        {
            List<T2> ls = new List<T2>();
            T2 t2 = new T2();
            t2.sparkid = 1000000000;
            t2.office = "";
            t2.sale = "XXX";
            t2.tcount = -1;
            t2.yq = 378.0000M;
            t2.transferdate = DateTime.Now;
            ls.Add(t2);
            dbHelper.BulkInsert(ls, "T2");
        }

the reult is 
1000000000	376.92	XXX	-1		2020-03-19 03:05:08
 t2.yq = 378.0000M;  BUT 376.92  is insert into clickhouse

if  i  set   t2.yq=0.0000M
the program  meet a exception, "Value was either too large or too small for an unsigned byte"
the  postion is 

public override void Write(ProtocolFormatter formatter, int rows) {
            Debug.Assert(Rows == rows, "Row count mismatch!");
            foreach (var d in Data) {
                var premultiplied = d * _exponent;
                if(_byteLength==4)
                    formatter.WriteBytes(BitConverter.GetBytes((int)premultiplied));
                else if(_byteLength==8)
                    formatter.WriteBytes(BitConverter.GetBytes((long)premultiplied));
                else {
                    byte c = (byte) (premultiplied > 0 ? 0 : 0xff);
                    if (c != 0) premultiplied = -premultiplied - 1;
                    for (var i = 0; i < _byteLength; i++) {
                        //  error is  below 
                        byte next = (byte) ((byte) (Math.Truncate(premultiplied) % 0xff) ^ c);
                        premultiplied = Math.Truncate(premultiplied / 0x100);
                        formatter.WriteByte(next);
                    }
                }
            }
        }

**Comment by killwort** [comment]
I cannot tell what goes wrong with 378->376.92 conversion, you'll need to provide the type you're using in database, e.g. Decimal(20,5). Most probably this is caused by the fact that .net decimal implementation is less precise than clickhouse's one.
As for inserting zeroes - i've fixed that.

**Comment by chenhunhun** [comment]
if the  field  is  defined Decimal(20, 4) , The problem is  meet  378->376.92 ,  if  i defined the field  Decimal64(2),  the  reuslt  is  correct.  thanks a lot!

**Comment by killwort** [comment]
I've ported 128 bit decimals to BigInteger implementation, now it works as designed without losing precision. Check ClickHouse.Ado.1.2.0-preview-02 nuget version.
