### ISSUE TITLE
Retrieve schema information from DB connection

### ISSUE THREAD

**Issue by phoenix-tr** [killwort/ClickHouse-Net#85]
We need to retrieve table columns' information from DB connection. Currently we are getting it from DB connection interfaces by using GetSchema interface but for Clickhouse it gives the following error;

> System.NotSupportedException: 'Specified method is not supported.'

For Oracle it returns related column information with their data types.

As a workaround we are writing our own query to get them like below;

`SELECT name ColumnName,
					CASE
					WHEN type LIKE ('%Int%') OR type LIKE ('%Float%') OR type LIKE ('%Decimal%') 
						THEN 'NUMBER'
					WHEN type LIKE ('%Date%')
						THEN 'DATE'
					ELSE 
						'STRING'
					END DataType
					FROM system.columns
					WHERE database = '{schemaName}' and table = '{tableNameWithoutSchema}'`

**Comment by phoenix-tr** [comment]
Wrong project. Sorry.

**Comment by killwort** [comment]
Clickhouse does not have schema introspection functions. The only thing you can do is to do `SHOW CREATE TABLE table` yet it returns SQL string used to create table - not very useful for machine reading.
