### ISSUE TITLE
Multiple insert command is not working

### ISSUE THREAD

**Issue by xcHades** [killwort/ClickHouse-Net#9]
Hello!

I'm trying to execute a multiple insert command (like `INSERT INTO Table (Col1, Col2, Col3) VALUES (Val1-1, Val1-2, Val1-3),(Val2-1, Val2-2, Val2-3)`), which is correctly works in clickhouse-client, but I get "Sequence contains no matching element" exception:
`System.Linq.Enumerable.First[TSource](IEnumerable 1 source, Func 2 predicate)
   ClickHouse.Ado.ClickHouseParameterCollection.get_Item(String parameterName)
   ClickHouse.Ado.ClickHouseCommand.<SubstituteParameters>b__28_0(Match m) 
   System.Text.RegularExpressions.RegexReplacement.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat)
   System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator, Int32 count, Int32 startat)
   System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   ClickHouse.Ado.ClickHouseCommand.SubstituteParameters(String commandText)
   ClickHouse.Ado.ClickHouseCommand.Execute(Boolean readResponse) 
   ClickHouse.Ado.ClickHouseCommand.ExecuteNonQuery() `
   

This exception occures in ClickHouseCommand.SubstituteParameters method, in which, as I understand, the program should not enter at all, since I do not pass any parameters. I would not really like to use hidden bulk-insert functionality because it's very undesirable to realize the GetEnumerator() for each entity. Could you explain why an exception may occur, is it a bug?

**Comment by killwort** [comment]
Do not use direct insert syntax, it is really inefficient. Use bulk insert functionality described in readme.md.

**Comment by killwort** [comment]
Regarding the exception, most likely that your data contains @ or : characters followed by letters/underscores which are interpreted as parameters *even if they are in quoted strings*. You should escape them by doubling.
