### ISSUE TITLE
No timeout on TcpClient connection

### ISSUE THREAD

**Issue by msvprogs** [killwort/ClickHouse-Net#94]
If clickhouse server is unavailable and doesn't respond to TCP commands, this line:
https://github.com/killwort/ClickHouse-Net/blob/a7b52b1f8cf000ebc5e2937e144e968b1ef9145f/ClickHouse.Ado/ClickHouseConnection.cs#L90

will hang forever. 

Timeout for Connect()/ConnectAsync() methods of TcpClient should be implemented manually: https://makolyte.com/how-to-set-a-timeout-for-tcpclient-connectasync/

**Comment by killwort** [comment]
Abandoning wait on connecting sockets is a bad idea, 'cause connection would still be made and the calling side will never know about that.

**Comment by killwort** [comment]
Yet it could be implemented :) Will be released in v.1.2.3
