### ISSUE TITLE
decimal128 not work

### ISSUE THREAD

**Issue by cn-cd-zhm** [killwort/ClickHouse-Net#96]
```
decimal128 can't be use, when sql is "select toDecimal128('123.123',6);". type name is 'decimal(38,6)'
```
[code there](https://github.com/killwort/ClickHouse-Net/search?q=Decimals+with+length&unscoped_q=Decimals+with+length)

**Comment by killwort** [comment]
Decimals with length more than 28 are not supported by the .NET Framework so there's no reason to support them here.
