### ISSUE TITLE
DateTime64 and time zone

### ISSUE THREAD

**Issue by lessenko** [killwort/ClickHouse-Net#98]
## Description
It's used: Ubuntu 18.04, ClickHouse 20.4.4.18, NET Core 3.1.3-1

## Steps to reproduce
1. cnn.CreateCommand("CREATE TABLE test_dt64 (k Date, dt64 DateTime64(5), dt64tz DateTime64(5,'Europe/Moscow'))  ENGINE = MergeTree(k, (dt64,dt64tz), 8192)").ExecuteNonQuery();
1. cnn.CreateCommand("INSERT INTO test_dt64 (k, dt64, dt64tz) VALUES ('2020-01-01','2020-01-01 00:00:00','2020-01-01 00:00:00')").ExecuteNonQuery();
1.  using (var cmd = cnn.CreateCommand("SELECT * FROM `test_dt64`"))
 { using (var reader = cmd.ExecuteReader()) PrintData(reader);}
_Output: 
Fields: k:Date dt64:DateTime64(5) dt64tz:DateTime64(5, ''Europe/Moscow'') 
1/1/2020 12:00:00 AM, 1/1/2020 3:00:00 AM, 1/1/2020 3:00:00 AM,_
1. clickhouse-client>
 `SELECT * FROM test_dt64;`
 Output:
_2020-01-01,    2020-01-01 06:00:00.00000,   2020-01-01 06:00:00.00000_ 

## Workarounds
  The datetime in the database differ by 3 or 6 hours (item 3. or 4.).  
To change time zone on server side I added line  `<timezone>UTC</timezone>`   in /etc/clickhouse-server/config.xml. it's received same results as in item 3 or 4.

Thanks.

**Comment by killwort** [comment]
I don't think there's any easy way to deal with the timezones stored in the database. Essentially clickhouse stores TZ info in column metadata, and actual data contains only the difference between stored date and unix epoch start (01-01-1970). My driver tries to use UTC everywhere as clickhouse's TZ names are not compatible with .net ones. So when you read data from column with TZ driver discards TZ info and returns .net DateTime with DateTimeKind.Universal (UTC) - that may lead to 1*TZ offset skew if you do not deal with TZ yourself. 2*tz offset may occur when you insert DateTime value with DateTimeKind.Local and read it again afterwards.

My advice is to remove TZ info from the database and store all values in the UTC format.

**Comment by lessenko** [comment]
Thanks. But I could not get a right result yet for DateTime64(5). I see two differences in data being written and read. The time differ by three hours, and after the point (for seconds) 3 characters are read (instead of 5).

`cnn.CreateCommand("CREATE TABLE test_dt64_utc (k Date, dt64 DateTime64(5))  ENGINE = MergeTree(k, (dt64), 8192)").ExecuteNonQuery();`

`cnn.CreateCommand("INSERT INTO test_dt64_utc (k, dt64) VALUES ('2020-01-01','2020-02-03 05:00:00.12345')").ExecuteNonQuery();`

The Reader uses the following formatter:
`string time_format = "yyyy-MM-dd HH:mm:ss.fffff";
DateTime val = reader.GetDateTime(1);
string tmp  = val.ToString(time_format);`

**Comment by lessenko** [comment]
I have installed UTC as default for ClickHouse Server (string   `<timezone>UTC</timezone>`    in  `config.xml` file and tested the driver with several queries:

1. `select now()`        -- the received time is UTC;
2. `select * from test` -- the received time is UTC;
3. `INSERT INTO test (dt64) VALUES ('2020-02-03 05:00:00.12345')` -- the received time differs by **three hours** from UTC. 

It's used: Ubuntu 18.04, ClickHouse  21.1.2.15, NET Core 5.0.
Thanks.

**Comment by killwort** [comment]
I've dealt with that. Surprisingly to me parsing DateTime from string with DateTimeStyles.AssumeUniversal changes the time from UTC to local TZ. I've changed parsing to use AssumeLocal, however my best advice is to use UTC both on the client and server and convert from/to local time only when displaying to the end-user. That will save you a lot of time debugging time skews.
