### ISSUE TITLE
Negative numerics issue

### ISSUE THREAD

**Issue by EvgenyVorobyev** [killwort/ClickHouse-Net#99]
## Description
Hi,
I found an issue with negative numerics. Could you fix it please?

## Steps to reproduce
1. Create test table
`CREATE TABLE tmp_DecimalTest (
`FixedDate` Date,
 `Amount1` Decimal(16,4),
 `Amount2` Decimal(20,8),
 `Amount3` Decimal(22,10)
) ENGINE = MergeTree PARTITION BY toYYYYMM(FixedDate) ORDER BY FixedDate SETTINGS index_granularity = 8192;`

2. Fill the table using code below:
`using ClickHouse.Ado;
using System;
using System.Collections;
using System.Collections.Generic;

namespace ClickHouseDecimalTest
{
    class Program
    {
        private static string _connectionString =
            "************************;";

        static void Main(string[] args)
        {
            var list = new List<MyPersistableObject>();

            list.Add(new MyPersistableObject()
            {
                MyDateField = DateTime.Now,
                MyDecimalField1 = (decimal) -100.0,
                MyDecimalField2 = (decimal) -100.0,
                MyDecimalField3 = (decimal) -100.0,
            });

            var connection = new ClickHouseConnection(_connectionString);
            connection.Open();
            var command = connection.CreateCommand();
            command.CommandText = "INSERT INTO tmp_DecimalTest (FixedDate,Amount1,Amount2,Amount3) VALUES @bulk";
            command.Parameters.Add(new ClickHouseParameter
            {
                ParameterName = "bulk",
                Value = list
            });
            command.ExecuteNonQuery();

        }
    }

    class MyPersistableObject : IEnumerable
    {
        public decimal MyDecimalField1;
        public decimal MyDecimalField2;
        public decimal MyDecimalField3;
        public DateTime MyDateField;

        public IEnumerator GetEnumerator()
        {
            yield return MyDateField;
            yield return MyDecimalField1;
            yield return MyDecimalField2;
            yield return MyDecimalField3;
        }
    }
}
`

3. Check table data. Fields Amount2 and Amount2 have wrong value (see attachement)

![decimal issue](https://user-images.githubusercontent.com/6521843/84164678-7c388680-aa7b-11ea-9533-25e3ae2d4736.PNG)

**Comment by EvgenyVorobyev** [comment]
Any feedback?

**Comment by killwort** [comment]
Well, there was an error for the negative decimals larger than 8 bytes. I've fixed that, will be released with v.1.2.3

**Comment by EvgenyVorobyev** [comment]
@killwort , could you change -100.00 to -40.96 and check results again?
![image](https://user-images.githubusercontent.com/6521843/93365428-73add400-f852-11ea-82c2-0bfacc653ecb.png)
I have installed v.1.2.3.
Do I need to open new issue?

**Comment by killwort** [comment]
Apparently I'm not very good at bit-arithmetic. It should be fixed now (1.2.4).

**Comment by EvgenyVorobyev** [comment]
@killwort , thanks for quick response!
Results are better, but there is a small discrepancy
![image](https://user-images.githubusercontent.com/6521843/93423697-3895ba00-f8bf-11ea-8238-3aa5e03c03b7.png)

**Comment by killwort** [comment]
1.2.5 fixes even smaller errors in numerics representation.
